language: csharp
mono: latest
dist: xenial
sudo: required
dotnet: 5.0.202
solution: QuickbooksSync.sln
install:
  - dotnet restore
  - nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./src/QbXml/QbXml.csproj
  - dotnet build -c Release --no-restore ./test/QbXml.Tests/QbXml.Tests.csproj
  - msbuild /p:Configuration=Release ./src/WebConnector/WebConnector.csproj
  - msbuild /p:Configuration=Release ./test/WebConnector.Tests/WebConnector.Tests.csproj
  - msbuild /p:Configuration=Release ./src/XsdGenerator/XsdGenerator.csproj
  - dotnet test -c Release --no-build ./test/QbXml.Tests/QbXml.Tests.csproj
  - dotnet test -c Release --no-build ./test/WebConnector.Tests/WebConnector.Tests.csproj
